-- ========================================
-- NM MART - COMPLETE PROJECT SCHEMA
-- PostgreSQL / Supabase Compatible
-- UUID-FREE VERSION
-- ========================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ========================================
-- CORE TENANT TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code TEXT NOT NULL UNIQUE,
    company_slug TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    owner_name TEXT,
    email TEXT,
    mobile TEXT,
    address TEXT,
    status TEXT DEFAULT 'active',
    plan TEXT DEFAULT 'starter',
    theme_config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- APP CONFIG
-- ========================================
CREATE TABLE IF NOT EXISTS app_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_pin TEXT DEFAULT crypt('1234', gen_salt('bf')),
    shop_name TEXT DEFAULT 'NM MART',
    address TEXT,
    mobile TEXT,
    email TEXT,
    gst_no TEXT,
    tax_rate NUMERIC DEFAULT 5,
    enable_guard_verification BOOLEAN DEFAULT false,
    primary_color TEXT DEFAULT '#FFC107',
    secondary_color TEXT DEFAULT '#212121',
    accent_color TEXT DEFAULT '#FF5722',
    logo_url TEXT,
    brand_name TEXT DEFAULT 'NM MART',
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS home_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_name TEXT NOT NULL,
    section_type TEXT,
    is_active BOOLEAN DEFAULT true,
    position INTEGER DEFAULT 0,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    image_url TEXT,
    link_url TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- CATALOG TABLES
-- ========================================
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (category_id, name)
);

CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL UNIQUE,
    code TEXT UNIQUE,
    description TEXT,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS unit_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL UNIQUE,
    code TEXT UNIQUE,
    short_name TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS department_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL UNIQUE,
    code TEXT UNIQUE,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL,
    mobile TEXT,
    email TEXT,
    address TEXT,
    gst_no TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- PRODUCTS
-- ========================================
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT,
    print_name TEXT,
    description TEXT,
    hsn_code TEXT,
    image_url TEXT,
    take_rate NUMERIC(10,2),
    retail_rate NUMERIC(10,2),
    delivery_rate NUMERIC(10,2),
    sale_rate NUMERIC DEFAULT 0,
    purchase_rate NUMERIC(10,2),
    mrp NUMERIC(10,2),
    stock NUMERIC DEFAULT 0,
    discount_percent NUMERIC(5,2),
    is_favourite BOOLEAN DEFAULT false,
    unit_name TEXT,
    category_name TEXT,
    brand_name TEXT,
    is_discountable BOOLEAN DEFAULT true,
    gst_percent NUMERIC(5,2),
    cess_percent NUMERIC(5,2),
    shop_id TEXT,
    is_package BOOLEAN DEFAULT false,
    narration TEXT,
    narration2 TEXT,
    item_status TEXT,
    itname TEXT,
    itnameprint TEXT,
    barcode TEXT,
    imagename TEXT,
    itemdescription TEXT,
    hsncode TEXT,
    picture TEXT,
    takerate NUMERIC(10,2),
    restrate NUMERIC(10,2),
    dlvrate NUMERIC(10,2),
    onlinerate NUMERIC(10,2),
    purcrate NUMERIC(10,2),
    opstock NUMERIC(10,2),
    discperc NUMERIC(5,2),
    isfav BOOLEAN DEFAULT false,
    unitcode TEXT,
    itg TEXT,
    itc TEXT,
    dtcode TEXT,
    kcode TEXT,
    brandcode TEXT,
    isdiscountable BOOLEAN DEFAULT true,
    gst NUMERIC(5,2),
    cess NUMERIC(5,2),
    shopid TEXT,
    ispackage BOOLEAN DEFAULT false,
    category_id BIGINT REFERENCES categories(id),
    subcategory_id BIGINT REFERENCES subcategories(id),
    brand_id BIGINT REFERENCES brands(id),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- USERS AND ACCOUNTS
-- ========================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT,
    email TEXT,
    phone TEXT,
    password_hash TEXT,
    address TEXT,
    pincode TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'admin',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS account_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL,
    mobile TEXT UNIQUE,
    email TEXT,
    address TEXT,
    address1 TEXT,
    address2 TEXT,
    pincode TEXT,
    gst_no TEXT,
    account_type TEXT DEFAULT 'Customer',
    opening_balance NUMERIC DEFAULT 0.00,
    current_balance NUMERIC DEFAULT 0.00,
    credit_days INTEGER DEFAULT 0,
    last_purchase_date TIMESTAMP WITH TIME ZONE,
    purchase_count INTEGER DEFAULT 0,
    total_purchases NUMERIC DEFAULT 0,
    rating NUMERIC DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS credit_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    account_id BIGINT REFERENCES account_master(id),
    account_name TEXT,
    cr_days INTEGER,
    cr_amount NUMERIC,
    mobile TEXT,
    name TEXT,
    address TEXT,
    amount NUMERIC NOT NULL DEFAULT 0.00,
    type TEXT NOT NULL DEFAULT 'Credit',
    reason TEXT,
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_boy_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    mobile TEXT,
    vehicle_type TEXT DEFAULT 'Motorcycle',
    status TEXT DEFAULT 'active',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_customer_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    address TEXT,
    pincode TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- PURCHASES / ORDERS
-- ========================================
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    invoice_no TEXT,
    supplier_id BIGINT REFERENCES suppliers(id),
    purchase_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    total_amount NUMERIC DEFAULT 0.00,
    paid_amount NUMERIC DEFAULT 0.00,
    balance_amount NUMERIC DEFAULT 0.00,
    remarks TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    purchase_id BIGINT REFERENCES purchases(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    quantity NUMERIC NOT NULL,
    rate NUMERIC NOT NULL,
    total NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    order_number TEXT,
    user_id TEXT,
    customer_name TEXT,
    user_mobile TEXT,
    address TEXT,
    pincode TEXT,
    subtotal NUMERIC NOT NULL,
    delivery_charge NUMERIC DEFAULT 0.00,
    discount NUMERIC DEFAULT 0.00,
    total_amount NUMERIC NOT NULL,
    payment_mode TEXT DEFAULT 'Online',
    payment_status TEXT DEFAULT 'pending',
    order_status TEXT DEFAULT 'pending',
    delivery_boy_id BIGINT REFERENCES delivery_boy_master(id),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    product_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    rate NUMERIC NOT NULL,
    total NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- WALLET / ADDRESS / COUPONS / OFFERS
-- ========================================
CREATE TABLE IF NOT EXISTS wallet_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT NOT NULL,
    balance NUMERIC DEFAULT 0.00,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL,
    reason TEXT,
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT,
    full_name TEXT NOT NULL,
    mobile TEXT NOT NULL,
    address_line1 TEXT NOT NULL,
    address_line2 TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT NOT NULL,
    is_default BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS pincode_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    pincode TEXT NOT NULL UNIQUE,
    city TEXT,
    state TEXT,
    delivery_charge NUMERIC DEFAULT 0.00,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    code TEXT NOT NULL UNIQUE,
    discount_type TEXT NOT NULL,
    discount_value NUMERIC NOT NULL,
    min_order_value NUMERIC DEFAULT 0.00,
    max_discount NUMERIC,
    usage_limit INTEGER,
    used_count INTEGER DEFAULT 0,
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS offers_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    discount_type TEXT,
    discount_value NUMERIC,
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- CART / WISHLIST / SUPPORT
-- ========================================
CREATE TABLE IF NOT EXISTS cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT NOT NULL,
    product_id BIGINT REFERENCES products(id),
    quantity NUMERIC DEFAULT 1.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS basket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT NOT NULL,
    product_id BIGINT REFERENCES products(id),
    quantity NUMERIC DEFAULT 1.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT NOT NULL,
    product_id BIGINT REFERENCES products(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_name TEXT,
    user_email TEXT,
    subject TEXT,
    message TEXT,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    title TEXT NOT NULL,
    message TEXT,
    type TEXT,
    reference_id TEXT,
    user_id TEXT,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    action TEXT NOT NULL,
    table_name TEXT,
    record_id TEXT,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- PAYMENT / EXPENSE / STOCK
-- ========================================
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    account_id BIGINT REFERENCES account_master(id),
    amount NUMERIC NOT NULL,
    payment_type TEXT NOT NULL,
    payment_mode TEXT,
    reference_no TEXT,
    notes TEXT,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    expense_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    category TEXT,
    description TEXT,
    amount NUMERIC NOT NULL,
    payment_mode TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    product_id BIGINT REFERENCES products(id),
    movement_type TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    reference_no TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    product_id BIGINT REFERENCES products(id),
    alert_type TEXT,
    threshold NUMERIC,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- CUSTOMER LOYALTY
-- ========================================
CREATE TABLE IF NOT EXISTS customer_loyalty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    user_id TEXT,
    customer_id BIGINT REFERENCES account_master(id),
    points NUMERIC DEFAULT 0,
    tier_id BIGINT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    loyalty_point_id BIGINT REFERENCES customer_loyalty(id),
    user_id TEXT,
    points NUMERIC,
    type TEXT,
    reason TEXT,
    reference_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    name TEXT NOT NULL,
    min_points NUMERIC,
    max_points NUMERIC,
    benefits TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- SYSTEM LOGS
-- ========================================
CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    table_name TEXT,
    action_type TEXT,
    username TEXT,
    user_role TEXT,
    old_data JSONB,
    new_data JSONB,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_code TEXT DEFAULT 'DEFAULT',
    product_id BIGINT REFERENCES products(id),
    old_stock NUMERIC,
    new_stock NUMERIC,
    change_type TEXT,
    reference_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- INDEXES
-- ========================================
ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS name TEXT,
    ADD COLUMN IF NOT EXISTS print_name TEXT,
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS hsn_code TEXT,
    ADD COLUMN IF NOT EXISTS image_url TEXT,
    ADD COLUMN IF NOT EXISTS take_rate NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS retail_rate NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS delivery_rate NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS sale_rate NUMERIC DEFAULT 0,
    ADD COLUMN IF NOT EXISTS purchase_rate NUMERIC(10,2),
    ADD COLUMN IF NOT EXISTS discount_percent NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS is_favourite BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS unit_name TEXT,
    ADD COLUMN IF NOT EXISTS category_name TEXT,
    ADD COLUMN IF NOT EXISTS brand_name TEXT,
    ADD COLUMN IF NOT EXISTS is_discountable BOOLEAN DEFAULT true,
    ADD COLUMN IF NOT EXISTS gst_percent NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS cess_percent NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS shop_id TEXT,
    ADD COLUMN IF NOT EXISTS is_package BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS item_status TEXT;

CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_shopid ON products(shopid);
CREATE INDEX IF NOT EXISTS idx_products_company_code ON products(company_code);
CREATE INDEX IF NOT EXISTS idx_products_tenant_id ON products(tenant_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_payments_account_id ON payments(account_id);
CREATE INDEX IF NOT EXISTS idx_expenses_expense_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_categories_company_code ON categories(company_code);
CREATE INDEX IF NOT EXISTS idx_brands_company_code ON brands(company_code);
CREATE INDEX IF NOT EXISTS idx_admin_users_company_code ON admin_users(company_code);
CREATE INDEX IF NOT EXISTS idx_system_logs_company_code ON system_logs(company_code);

-- ========================================
-- SEEDS
-- ========================================
INSERT INTO companies (company_code, company_slug, company_name, owner_name, email, mobile, address, status, plan)
VALUES ('DEFAULT', 'default', 'NM MART Default', 'Admin', 'info@nmart.com', '9999999999', 'Main Market', 'active', 'starter')
ON CONFLICT (company_code) DO NOTHING;

INSERT INTO app_config (shop_name, brand_name, address, mobile, email, gst_no, tax_rate, company_code)
VALUES ('NM MART', 'NM MART', 'Main Market', '9999999999', 'info@nmart.com', '27AAAA0000A1Z5', 5, 'DEFAULT')
ON CONFLICT DO NOTHING;

INSERT INTO admin_users (username, password, full_name, role, is_active, company_code)
VALUES ('admin', 'admin123', 'Admin User', 'super_admin', true, 'DEFAULT')
ON CONFLICT (username) DO NOTHING;

INSERT INTO categories (name, is_active, company_code)
VALUES ('General', true, 'DEFAULT')
ON CONFLICT (name) DO NOTHING;

INSERT INTO brands (name, is_active, company_code)
VALUES ('Generic', true, 'DEFAULT')
ON CONFLICT (name) DO NOTHING;

INSERT INTO unit_master (name, code, short_name, is_active, company_code)
VALUES ('Piece', 'PCS', 'PCS', true, 'DEFAULT')
ON CONFLICT (name) DO NOTHING;

INSERT INTO department_master (name, code, is_active, company_code)
VALUES ('General', 'GEN', true, 'DEFAULT')
ON CONFLICT (name) DO NOTHING;

-- ========================================
-- RLS BASIC POLICIES
-- ========================================
CREATE OR REPLACE FUNCTION public.current_company_code()
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(
    NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'company_code', ''),
    NULLIF(current_setting('request.jwt.claims', true)::jsonb ->> 'companyCode', ''),
    'DEFAULT'
  );
$$;

CREATE OR REPLACE FUNCTION public.matches_company_scope(p_company_code text)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT (
    auth.role() = 'service_role'
    OR COALESCE(p_company_code, 'DEFAULT') = 'DEFAULT'
    OR public.current_company_code() = COALESCE(p_company_code, 'DEFAULT')
  );
$$;

DO $$
DECLARE
  tbl text;
  policy_name text;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY[
    'companies', 'products', 'admin_users', 'categories', 'subcategories', 'brands',
    'unit_master', 'department_master', 'suppliers', 'stock_alerts', 'hsn_master',
    'account_master', 'purchases', 'purchase_items', 'inventory_logs', 'delivery_boy_master',
    'delivery_customer_master', 'users', 'credit_master', 'orders', 'order_items',
    'wallet_master', 'wallet_transactions', 'expense_categories', 'expenses', 'addresses',
    'pincode_master', 'banners', 'coupons', 'offers_master', 'home_config', 'app_config',
    'customer_loyalty', 'loyalty_transactions', 'loyalty_tiers', 'cart', 'wishlist',
    'system_logs', 'notifications', 'support_tickets'
  ]) LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    policy_name := tbl || '_tenant_policy';
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_name, tbl);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL USING (public.matches_company_scope(COALESCE(company_code, ''DEFAULT''))) WITH CHECK (public.matches_company_scope(COALESCE(company_code, ''DEFAULT'')))',
      policy_name,
      tbl
    );
  END LOOP;
END $$;
