import type { PersistenceActions } from '../types/persistence.types';

export const createPersistenceActions = (
  setPersistenceId: (persistenceId: string | null) => void,
  setPersistenceStatus: (status: any) => void,
  setCurrentEntity: (entity: string | null) => void,
  setPersisting: (isPersisting: boolean) => void,
  setStartedAt: (startedAt: string | null) => void,
  setFinishedAt: (finishedAt: string | null) => void,
  setLoading: (loading: boolean) => void,
  setError: (error: string) => void,
  resetPersistence: () => void,
  setExecutionReference: (reference: any | null) => void,
  setRuntimeReference: (reference: any | null) => void,
  setCheckoutReference: (reference: any | null) => void,
  setOrderReference: (reference: any | null) => void,
  setInvoiceReference: (reference: any | null) => void,
  setPrinterReference: (reference: any | null) => void,
  processPersistence: () => Promise<void>,
  processExecution: () => Promise<void>,
  executePersistence: () => Promise<void>,
  processRepository: () => Promise<void>,
  saveAll: () => Promise<void>
): PersistenceActions => ({
  setPersistenceId,
  setPersistenceStatus,
  setCurrentEntity,
  setPersisting,
  setStartedAt,
  setFinishedAt,
  setLoading,
  setError,
  resetPersistence,
  setExecutionReference,
  setRuntimeReference,
  setCheckoutReference,
  setOrderReference,
  setInvoiceReference,
  setPrinterReference,
  processPersistence,
  processExecution,
  executePersistence,
  processRepository,
  saveAll
});
