import type { ExecutionActions, ExecutionProcessResult } from '../types/execution.types';

export const createExecutionActions = (
  setExecutionId: (executionId: string | null) => void,
  setExecutionStatus: (status: any) => void,
  setRuntimeReference: (reference: any | null) => void,
  setCartReference: (reference: any | null) => void,
  setCustomerReference: (reference: any | null) => void,
  setCheckoutReference: (reference: any | null) => void,
  setOrderReference: (reference: any | null) => void,
  setInvoiceReference: (reference: any | null) => void,
  setPrinterReference: (reference: any | null) => void,
  setCurrentPhase: (phase: string | null) => void,
  setStartedAt: (startedAt: string | null) => void,
  setFinishedAt: (finishedAt: string | null) => void,
  setLoading: (loading: boolean) => void,
  setError: (error: string) => void,
  resetExecution: () => void,
  processExecution: () => Promise<void>,
  resetExecutionProcess: () => void,
  startExecution: () => Promise<void>,
  processCheckout: () => Promise<void>,
  processOrder: () => Promise<void>,
  processInvoice: () => Promise<void>,
  processPrinter: () => Promise<void>,
  executeSale: () => Promise<void>,
  persistExecution: () => Promise<void>
): ExecutionActions => ({
  setExecutionId,
  setExecutionStatus,
  setRuntimeReference,
  setCartReference,
  setCustomerReference,
  setCheckoutReference,
  setOrderReference,
  setInvoiceReference,
  setPrinterReference,
  setCurrentPhase,
  setStartedAt,
  setFinishedAt,
  setLoading,
  setError,
  resetExecution,
  processExecution,
  resetExecutionProcess,
  startExecution,
  processCheckout,
  processOrder,
  processInvoice,
  processPrinter,
  executeSale,
  persistExecution
});
