-- Step 1: Rename existing products table to keep a backup
ALTER TABLE products RENAME TO products_backup_20260711;

-- Step 2: Create new products table with all required columns
CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    barcode TEXT UNIQUE,
    name TEXT NOT NULL,
    itname TEXT,
    itnameprint TEXT,
    print_name TEXT,
    category_id UUID REFERENCES categories(id),
    category_name TEXT,
    subcategory_id UUID REFERENCES subcategories(id),
    subcategory_name TEXT,
    brand_id UUID REFERENCES brands(id),
    brand_name TEXT,
    brand_code TEXT,
    brandcode TEXT,
    unit_id UUID REFERENCES unit_master(id),
    unit_name TEXT,
    unitcode TEXT,
    department_id UUID REFERENCES department_master(id),
    department_code TEXT,
    dtcode TEXT,
    hsn_code TEXT,
    hsncode TEXT,
    mrp NUMERIC DEFAULT 0,
    sale_rate NUMERIC DEFAULT 0,
    purchase_rate NUMERIC DEFAULT 0,
    purcrate NUMERIC DEFAULT 0,
    take_rate NUMERIC DEFAULT 0,
    takerate NUMERIC DEFAULT 0,
    retail_rate NUMERIC DEFAULT 0,
    restrate NUMERIC DEFAULT 0,
    delivery_rate NUMERIC DEFAULT 0,
    dlvrate NUMERIC DEFAULT 0,
    online_rate NUMERIC DEFAULT 0,
    onlinerate NUMERIC DEFAULT 0,
    basic_sale_price NUMERIC DEFAULT 0,
    gst NUMERIC DEFAULT 0,
    gst_percent NUMERIC DEFAULT 0,
    cess NUMERIC DEFAULT 0,
    cess_percent NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    discount_pct NUMERIC DEFAULT 0,
    discount_percent NUMERIC DEFAULT 0,
    discperc NUMERIC DEFAULT 0,
    min_qty NUMERIC DEFAULT 1,
    stock NUMERIC DEFAULT 0,
    opstock NUMERIC DEFAULT 0,
    description TEXT,
    itemdescription TEXT,
    image_url TEXT,
    picture TEXT,
    imagename TEXT,
    size TEXT,
    color TEXT,
    counter_name TEXT,
    item_group TEXT,
    itg TEXT,
    item_category TEXT,
    itc TEXT,
    k_code TEXT,
    kcode TEXT,
    shop_id TEXT,
    shopid TEXT,
    is_package TEXT DEFAULT 'No',
    ispackage TEXT DEFAULT 'No',
    narration TEXT,
    narration2 TEXT,
    item_status TEXT DEFAULT 'Active',
    itemstatus TEXT DEFAULT 'Active',
    is_favourite TEXT DEFAULT 'No',
    isfav TEXT DEFAULT 'No',
    is_discountable TEXT DEFAULT 'Yes',
    isdiscountable TEXT DEFAULT 'Yes',
    is_active BOOLEAN DEFAULT true,
    is_live_on_app BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Step 3: Copy data from backup table to new table (preserve existing data)
INSERT INTO products (
    id, barcode, name, itname, print_name, category_id, category_name, subcategory_id, subcategory_name,
    brand_id, brand_name, brand_code, unit_id, unit_name, department_id, department_code, hsn_code,
    mrp, sale_rate, purchase_rate, take_rate, retail_rate, delivery_rate, online_rate,
    basic_sale_price, gst_percent, cess_percent, discount, discount_pct, discount_percent, min_qty,
    stock, opstock, description, image_url, size, color, counter_name, item_group, item_category,
    k_code, shop_id, is_package, narration, narration2, item_status, is_favourite,
    is_discountable, is_active, is_live_on_app, created_at, updated_at
) SELECT 
    id, barcode, name, itname, print_name, category_id, category_name, subcategory_id, subcategory_name,
    brand_id, brand_name, brand_code, unit_id, unit_name, department_id, department_code, hsn_code,
    mrp, sale_rate, purchase_rate, take_rate, retail_rate, delivery_rate, online_rate,
    basic_sale_price, gst_percent, cess_percent, discount, discount_pct, discount_percent, min_qty,
    stock, opstock, description, image_url, size, color, counter_name, item_group, item_category,
    k_code, shop_id, is_package, narration, narration2, item_status, is_favourite,
    is_discountable, is_active, is_live_on_app, created_at, updated_at
FROM products_backup_20260711;

-- Step 4: Recreate readable_products view with all columns
CREATE OR REPLACE VIEW readable_products AS
SELECT 
    name,
    itname,
    itnameprint,
    print_name,
    barcode,
    imagename,
    itemdescription,
    description,
    hsncode,
    hsn_code,
    picture,
    image_url,
    takerate,
    take_rate,
    restrate,
    retail_rate,
    dlvrate,
    delivery_rate,
    onlinerate,
    online_rate,
    sale_rate,
    purcrate,
    purchase_rate,
    mrp,
    opstock,
    stock,
    discperc,
    discount_pct,
    discount_percent,
    discount,
    isfav,
    is_favourite,
    unitcode,
    unit_name,
    itg,
    item_group,
    itc,
    item_category,
    category_name,
    dtcode,
    department_code,
    kcode,
    k_code,
    brandcode,
    brand_code,
    brand_name,
    isdiscountable,
    is_discountable,
    gst,
    gst_percent,
    cess,
    cess_percent,
    shopid,
    shop_id,
    ispackage,
    is_package,
    narration,
    narration2,
    itemstatus,
    item_status,
    is_active,
    is_live_on_app,
    created_at,
    updated_at
FROM products
ORDER BY created_at DESC;

-- Optional Step 5: After verifying data is correct, you can drop the backup table
-- DROP TABLE products_backup_20260711;
