-- Step 1: Rename backup table back to products (if it exists
ALTER TABLE products_backup_20260711 RENAME TO products;

-- Step 2: Now run the safe migration 002 to add missing columns
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS itnameprint TEXT,
ADD COLUMN IF NOT EXISTS imagename TEXT,
ADD COLUMN IF NOT EXISTS itemdescription TEXT,
ADD COLUMN IF NOT EXISTS hsncode TEXT,
ADD COLUMN IF NOT EXISTS picture TEXT,
ADD COLUMN IF NOT EXISTS takerate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS restrate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS dlvrate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS purcrate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS discperc NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS isfav TEXT DEFAULT 'No',
ADD COLUMN IF NOT EXISTS unitcode TEXT,
ADD COLUMN IF NOT EXISTS itg TEXT,
ADD COLUMN IF NOT EXISTS itc TEXT,
ADD COLUMN IF NOT EXISTS dtcode TEXT,
ADD COLUMN IF NOT EXISTS kcode TEXT,
ADD COLUMN IF NOT EXISTS brandcode TEXT,
ADD COLUMN IF NOT EXISTS isdiscountable TEXT DEFAULT 'Yes',
ADD COLUMN IF NOT EXISTS gst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cess NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS shopid TEXT,
ADD COLUMN IF NOT EXISTS ispackage TEXT DEFAULT 'No',
ADD COLUMN IF NOT EXISTS narration TEXT,
ADD COLUMN IF NOT EXISTS narration2 TEXT,
ADD COLUMN IF NOT EXISTS itemstatus TEXT DEFAULT 'Active';

-- Step 3: Update readable_products view
CREATE OR REPLACE VIEW readable_products AS
SELECT 
    name,
    itname,
    itnameprint,
    print_name,
    barcode,
    imagename,
    itemdescription,
    description,
    hsncode,
    hsn_code,
    picture,
    image_url,
    takerate,
    take_rate,
    restrate,
    retail_rate,
    dlvrate,
    delivery_rate,
    onlinerate,
    online_rate,
    sale_rate,
    purcrate,
    purchase_rate,
    mrp,
    opstock,
    stock,
    discperc,
    discount_pct,
    discount_percent,
    discount,
    isfav,
    is_favourite,
    unitcode,
    unit_name,
    itg,
    item_group,
    itc,
    item_category,
    category_name,
    dtcode,
    department_code,
    kcode,
    k_code,
    brandcode,
    brand_code,
    brand_name,
    isdiscountable,
    is_discountable,
    gst,
    gst_percent,
    cess,
    cess_percent,
    shopid,
    shop_id,
    ispackage,
    is_package,
    narration,
    narration2,
    itemstatus,
    item_status,
    is_active,
    is_live_on_app,
    created_at,
    updated_at
FROM products
ORDER BY created_at DESC;
