import type { Cart } from '../types/cart.types';

export const initialCartState: Cart = {
  id: '',
  items: [],
  selectedItem: null,
  subtotal: 0,
  discount: 0,
  discountType: null,
  discountValue: null,
  subtotalAfterDiscount: 0,
  tax: 0,
  gstMode: null,
  gstRate: null,
  cgst: 0,
  sgst: 0,
  igst: 0,
  grandTotal: 0,
  roundOff: 0,
  payableAmount: 0,
  totalQty: 0,
  totalItems: 0,
  customerId: null,
  notes: '',
  status: 'empty',
  loading: false,
  error: null,
  lastUpdated: null,
};
