import type { RuntimeActions } from '../types/runtime.types';

export const createRuntimeActions = (
  setRuntimeId: (runtimeId: string | null) => void,
  setRuntimeStatus: (status: any) => void,
  setCurrentModule: (module: string | null) => void,
  setRunning: (isRunning: boolean) => void,
  setStartedAt: (startedAt: string | null) => void,
  setFinishedAt: (finishedAt: string | null) => void,
  setLoading: (loading: boolean) => void,
  setError: (error: string) => void,
  resetRuntime: () => void,
  setCartReference: (reference: any | null) => void,
  setCustomerReference: (reference: any | null) => void,
  setCheckoutReference: (reference: any | null) => void,
  setOrderReference: (reference: any | null) => void,
  setInvoiceReference: (reference: any | null) => void,
  setPrinterReference: (reference: any | null) => void,
  startRuntime: () => void,
  stopRuntime: () => void,
  restartRuntime: () => void,
  validateRuntime: () => void,
  clearValidation: () => void,
  processRuntime: () => void,
  resetRuntimeProcess: () => void
): RuntimeActions => ({
  setRuntimeId,
  setRuntimeStatus,
  setCurrentModule,
  setRunning,
  setStartedAt,
  setFinishedAt,
  setLoading,
  setError,
  resetRuntime,
  setCartReference,
  setCustomerReference,
  setCheckoutReference,
  setOrderReference,
  setInvoiceReference,
  setPrinterReference,
  startRuntime,
  stopRuntime,
  restartRuntime,
  validateRuntime,
  clearValidation,
  processRuntime,
  resetRuntimeProcess
});
